// swift-tools-version:5.10
// SPDX-FileCopyrightText: 2026 Maiko BOSSUYT
// SPDX-License-Identifier: GPL-3.0-or-later
// RelayTitleCatalog — Relay's offline game title catalog (cover art, 2026-09-27).
//
// A read-only SQLite generated by Scripts/relay-title-catalog.py from pinned
// libretro-database DATs (CC-BY-SA-4.0) and the MetadataProvider over it.
// Linked only by the app targets: the resource never reaches extensions.
import PackageDescription

let package = Package(
    name: "RelayTitleCatalog",
    platforms: [.iOS(.v17), .tvOS(.v17), .macOS(.v14)],
    products: [.library(name: "RelayTitleCatalog", targets: ["RelayTitleCatalog"])],
    dependencies: [
        .package(path: "../RelayDomain"),
        .package(path: "../RelayLibrary"),
        .package(path: "../RelayPersistence"),
        .package(url: "https://github.com/groue/GRDB.swift.git", exact: "7.11.1"),
    ],
    targets: [
        .target(
            name: "RelayTitleCatalog",
            dependencies: [
                .product(name: "RelayDomain", package: "RelayDomain"),
                .product(name: "RelayLibrary", package: "RelayLibrary"),
                .product(name: "GRDB", package: "GRDB.swift"),
            ],
            resources: [.copy("Resources/RelayTitles.sqlite")],
            swiftSettings: [.enableExperimentalFeature("StrictConcurrency")]
        ),
        .testTarget(name: "RelayTitleCatalogTests", dependencies: [
            "RelayTitleCatalog",
            .product(name: "RelayPersistence", package: "RelayPersistence"),
        ]),
    ]
)
