// SPDX-FileCopyrightText: 2026 Maiko BOSSUYT
// SPDX-License-Identifier: GPL-3.0-or-later
//  AboutRelayView.swift
//  RelayUI
//
//  Settings ▸ About Relay ▸ Open Source & Licenses.
//
//  The About screen states what Relay is in four short lines that are true of
//  the build the player is holding (open source, no ads, no tracking, local
//  library) and opens the licence screen. The licence screen lists every
//  component actually distributed in the app, by category, from the generated
//  dataset; a component's page shows its version, licence, copyright,
//  upstream, Relay's modifications and the full licence text. Nothing here is
//  typed by hand: the dataset is `licenses.json`, generated by
//  Scripts/relay-licenses.py from the manifests.

import SwiftUI
import RelayDesignSystem

// MARK: - About Relay

public struct AboutRelayView: View {
    private let dataset = LicensesDataset.bundled()

    public init() {}

    public var body: some View {
        List {
            Section {
                SettingsLockup(version: SettingsView.versionString)
                    .listRowBackground(Color.clear)
            }

            Section {
                VStack(alignment: .leading, spacing: RelaySpacing.xs) {
                    Text("Open source. No ads. No tracking.", bundle: .module)
                        .font(.relayCardTitle)
                        .foregroundStyle(RelayColor.textPrimary)
                    Text("Your library stays yours.", bundle: .module)
                        .font(.relayCardTitle)
                        .foregroundStyle(RelayColor.textPrimary)
                    Text("Relay's source code is free software under the GNU GPL, version 3 or later. Your library stays yours, on your devices and in your chosen sync service. Relay includes no games: bring the files you own.", bundle: .module)
                        .font(.relayCallout)
                        .foregroundStyle(RelayColor.textSecondary)
                        .padding(.top, RelaySpacing.xxs)
                }
                .padding(.vertical, RelaySpacing.xxs)
            }

            Section {
                NavigationLink(value: Route.openSource) {
                    Label { Text("Open Source & Licenses", bundle: .module) } icon: { Image(systemName: "chevron.left.forwardslash.chevron.right") }
                }
                RepositoryLink(.sourceCode, title: L("Source Code"), dataset: dataset)
                RepositoryLink(.relayLicense, title: L("Relay License"), dataset: dataset)
                RepositoryLink(.thirdParty, title: L("Third-Party Software"), dataset: dataset)
                RepositoryLink(.trademarks, title: L("Trademark Policy"), dataset: dataset)
            } header: {
                SettingsHeader(L("Open source"))
            } footer: {
                Text("The Relay name, the Baton mark and the app icon are Relay's own and stay with the official app.", bundle: .module)
            }
        }
        .relaySettingsPage(L("About Relay"))
    }
}

/// A row that opens a repository document. On Apple TV, which has no browser,
/// it shows the address so the player can open it elsewhere.
private struct RepositoryLink: View {
    let link: LicensesDataset.Link
    let title: String
    let dataset: LicensesDataset?

    init(_ link: LicensesDataset.Link, title: String, dataset: LicensesDataset?) {
        self.link = link; self.title = title; self.dataset = dataset
    }

    private var url: URL { link.url(repository: dataset?.sourceRepository ?? "https://github.com/relayemu/client") }

    var body: some View {
        #if os(tvOS)
        VStack(alignment: .leading, spacing: 2) {
            Text(title).foregroundStyle(RelayColor.textPrimary)
            Text(url.absoluteString).font(.relayMeta).foregroundStyle(RelayColor.textSecondary)
        }
        .accessibilityElement(children: .combine)
        #else
        Link(destination: url) {
            HStack {
                Text(title).foregroundStyle(RelayColor.textPrimary)
                Spacer()
                Image(systemName: "arrow.up.right").foregroundStyle(RelayColor.textTertiary)
            }
        }
        .accessibilityHint(Text(url.absoluteString))
        #endif
    }
}

// MARK: - Open Source & Licenses

public struct OpenSourceView: View {
    let dataset: LicensesDataset?

    public init(dataset: LicensesDataset? = LicensesDataset.bundled()) {
        self.dataset = dataset
    }

    public var body: some View {
        List {
            if let dataset {
                Section {
                    Text("Every component distributed in Relay \(dataset.relayVersion), with its exact version and licence. Relay's own code is \(dataset.relayLicense).", bundle: .module)
                        .font(.relayCallout)
                        .foregroundStyle(RelayColor.textSecondary)
                }
                ForEach(dataset.categories) { category in
                    Section {
                        ForEach(category.components) { component in
                            NavigationLink(value: Route.licenseComponent(component.id)) {
                                ComponentRow(component: component)
                            }
                        }
                    } header: {
                        SettingsHeader(categoryTitle(category.id, fallback: category.title))
                    }
                }
            } else {
                Section {
                    Text("The licence list is missing from this build.", bundle: .module)
                        .foregroundStyle(RelayColor.textSecondary)
                }
            }
        }
        .relaySettingsPage(L("Open Source & Licenses"))
    }

    /// Category titles are localised here; the dataset's English titles are the fallback.
    private func categoryTitle(_ id: String, fallback: String) -> String {
        switch id {
        case "cores": return L("Emulator Cores")
        case "relay": return L("Relay Libraries")
        case "libraries": return L("Third-Party Libraries")
        case "media": return L("Media & Rendering")
        case "data": return L("Game Catalog")
        default: return fallback
        }
    }
}

private struct ComponentRow: View {
    let component: LicensesDataset.Component

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(component.name).foregroundStyle(RelayColor.textPrimary)
            Text(verbatim: "\(component.versionLabel) · \(component.license)")
                .font(.relayMeta)
                .foregroundStyle(RelayColor.textSecondary)
                .lineLimit(1)
        }
        .accessibilityElement(children: .combine)
    }
}

// MARK: - Component detail

public struct ComponentDetailView: View {
    let component: LicensesDataset.Component

    public init(component: LicensesDataset.Component) { self.component = component }

    public var body: some View {
        #if os(tvOS)
        // Information only: focus must stay on this page so the remote scrolls the
        // metadata and Menu returns to Open Source & Licenses (B2-TV-002).
        TVInfoPage(title: component.name) {
            TVInfoSection(header: component.name, footer: component.description) {
                detail(L("Version"), component.versionLabel)
                detail(L("License"), component.licenseName + (component.licenseNote.map { " — \($0)" } ?? ""))
                detail(L("Copyright"), component.copyright)
                if let systems = component.systems, !systems.isEmpty {
                    detail(L("Systems"), systems.joined(separator: ", "))
                }
                upstreamRow
                if let base = component.upstreamBase { detail(L("Based on"), base) }
                if let modifications = component.modifications { detail(L("Relay modifications"), modifications) }
                if let location = component.sourceLocation { detail(L("Source in the repository"), location) }
            }
            if !component.licenseText.isEmpty {
                TVInfoSection(header: L("License text")) { licenseBody(component.licenseText) }
            }
            if let notice = component.noticeText, !notice.isEmpty {
                TVInfoSection(header: L("Notice")) { licenseBody(notice) }
            }
        }
        #else
        List {
            Section {
                detail(L("Version"), component.versionLabel)
                detail(L("License"), component.licenseName + (component.licenseNote.map { " — \($0)" } ?? ""))
                detail(L("Copyright"), component.copyright)
                if let systems = component.systems, !systems.isEmpty {
                    detail(L("Systems"), systems.joined(separator: ", "))
                }
                upstreamRow
                if let base = component.upstreamBase { detail(L("Based on"), base) }
                if let modifications = component.modifications { detail(L("Relay modifications"), modifications) }
                if let location = component.sourceLocation { detail(L("Source in the repository"), location) }
            } header: {
                SettingsHeader(component.name)
            } footer: {
                Text(component.description)
            }

            if !component.licenseText.isEmpty {
                Section {
                    Text(component.licenseText)
                        .font(.system(.footnote, design: .monospaced))
                        .foregroundStyle(RelayColor.textSecondary)
                        .relaySelectable()
                } header: {
                    SettingsHeader(L("License text"))
                }
            }
            if let notice = component.noticeText, !notice.isEmpty {
                Section {
                    Text(notice)
                        .font(.system(.footnote, design: .monospaced))
                        .foregroundStyle(RelayColor.textSecondary)
                        .relaySelectable()
                } header: {
                    SettingsHeader(L("Notice"))
                }
            }
        }
        .relaySettingsPage(component.name)
        #endif
    }

    private func licenseBody(_ text: String) -> some View {
        Text(text)
            .font(.system(.footnote, design: .monospaced))
            .foregroundStyle(RelayColor.textSecondary)
            .relaySelectable()
            .fixedSize(horizontal: false, vertical: true)
    }

    @ViewBuilder
    private var upstreamRow: some View {
        #if os(tvOS)
        detail(L("Upstream"), component.upstream)
        #else
        if let url = URL(string: component.upstream), url.scheme?.hasPrefix("http") == true {
            Link(destination: url) {
                VStack(alignment: .leading, spacing: 2) {
                    Text(L("Upstream")).font(.relayMeta).foregroundStyle(RelayColor.textSecondary)
                    Text(component.upstream).foregroundStyle(RelayColor.textPrimary)
                }
            }
        } else {
            detail(L("Upstream"), component.upstream)
        }
        #endif
    }

    private func detail(_ title: String, _ value: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(title).font(.relayMeta).foregroundStyle(RelayColor.textSecondary)
            Text(value).foregroundStyle(RelayColor.textPrimary).relaySelectable()
        }
        .accessibilityElement(children: .combine)
    }
}

private extension View {
    /// Text selection where the platform has it; Apple TV has no pointer or clipboard.
    @ViewBuilder
    func relaySelectable() -> some View {
        #if os(tvOS)
        self
        #else
        self.textSelection(.enabled)
        #endif
    }
}
