// SPDX-FileCopyrightText: 2026 Maiko BOSSUYT
// SPDX-License-Identifier: GPL-3.0-or-later

import SwiftUI

public enum RelaySymbol: String, Sendable {
    case play = "play.fill"
    case quickSave = "square.and.arrow.down.fill"
    case loadState = "clock.arrow.circlepath"
    case rewind = "backward.fill"
    case speed = "forward.fill"
    case display = "rectangle.on.rectangle"
    case controller = "gamecontroller.fill"
    case controllerDisconnected = "gamecontroller"
    case cheats = "wand.and.stars"
    case achievements = "trophy.fill"
    case gameSettings = "slider.horizontal.3"
    case exitGame = "xmark.circle"
    case favorite = "heart"
    case favoriteFilled = "heart.fill"
    case firmware = "cpu"
    case importFiles = "plus"
    case importEmpty = "square.and.arrow.down.on.square"
    case search = "magnifyingglass"
    case settings = "gearshape"
    case pro = "sparkles"
    case more = "ellipsis"
    case delete = "trash"
    case info = "info.circle"
    case caution = "exclamationmark.triangle.fill"
    case critical = "xmark.octagon.fill"
    case positive = "checkmark.seal.fill"
    case sort = "arrow.up.arrow.down"
    case grid = "square.grid.2x2"
    case list = "list.bullet"
    case home = "house"
    case library = "square.grid.2x2.fill"
    case systems = "rectangle.3.group"
    case showInFinder = "folder"
    case deviceIPhone = "iphone.gen3"
    case deviceIPad = "ipad"
    case deviceAppleTV = "appletv.fill"
    case deviceMac = "macbook"
    case saved = "checkmark.circle.fill"
    case keyboard = "keyboard"
    case touch = "hand.tap"
    case pause = "pause.fill"
    case recording = "record.circle"
    case fullScreen = "arrow.up.left.and.arrow.down.right"
    case upToDate = "checkmark.icloud"
    case syncing = "arrow.triangle.2.circlepath.icloud"
    case inCloud = "icloud.and.arrow.down"
    case notSynced = "exclamationmark.icloud"
    case conflict = "exclamationmark.icloud.fill"
    case storageFull = "externaldrive.badge.exclamationmark"
    case cloudOff = "icloud.slash"
    case removeDownload = "xmark.icloud"
    case download = "arrow.down.circle"
    case deviceUnknown = "desktopcomputer"
    // Covers (cover-art spec §3)
    case chooseCover = "photo"
    case photos = "photo.on.rectangle"
    case resetCover = "arrow.uturn.backward"

    public var image: Image { Image(systemName: rawValue) }
}
